asyncapi: 3.0.0
info:
  title: Order API
  version: 1.0.0
servers:
  development_kafka:
    host: localhost:1234
    protocol: kafka
    security:
      - type: userPassword
        description: SASL/PLAIN security
        x-sasl:
          username: admin
          password: admin-secret
  development_pub_sub:
    host: localhost:1234
    protocol: googlepubsub
    security:
      - type: oauth2
        description: Google Pub Sub security
        flows:
          clientCredentials:
            tokenUrl: https://oauth2.googleapis.com/token
        x-pubsub:
          credentialsPath: '~/.config/gcloud/application_default_credentials.json'
channels:
  NewOrderPlaced:
    address: place-order
    messages:
      placeOrder.message:
        $ref: '#/components/messages/OrderRequest'
  NewOrderProcessed:
    address: process-order
    messages:
      processOrder.message:
        $ref: '#/components/messages/Order'
  OrderCancellationRequested:
    address: cancel-order
    messages:
      cancelOrder.message:
        $ref: '#/components/messages/CancelOrderRequest'
  OrderCancellationProcessed:
    address: process-cancellation
    messages:
      processCancellation.message:
        $ref: '#/components/messages/CancellationReference'
  NotifyOrderUpdates:
    address: notify-order
    messages:
      notifyOrder.message:
        $ref: '#/components/messages/NotifyOrder'
  OrderDeliveryInitiated:
    address: initiate-order-delivery
    messages:
      orderDeliveryInitiation.message:
        $ref: '#/components/messages/OrderDeliveryInitiationTrigger'
operations:
  placeOrder:
    action: receive
    channel:
      $ref: '#/channels/NewOrderPlaced'
    messages:
      - $ref: '#/channels/NewOrderPlaced/messages/placeOrder.message'
    reply:
      channel:
        $ref: '#/channels/NewOrderProcessed'
      messages:
        - $ref: '#/channels/NewOrderProcessed/messages/processOrder.message'
  cancelOrder:
    action: receive
    channel:
      $ref: '#/channels/OrderCancellationRequested'
    messages:
      - $ref: '#/channels/OrderCancellationRequested/messages/cancelOrder.message'
    reply:
      channel:
        $ref: '#/channels/OrderCancellationProcessed'
      messages:
        - $ref: '#/channels/OrderCancellationProcessed/messages/processCancellation.message'
  notifyOrder:
    action: send
    x-specmatic-trigger:
      command: >
        curl -s -X PUT http://localhost:9000/orders
        -H "Content-Type: application/json"
        -d '{"id":123,"status":"PROCESSED","timestamp":"2025-04-12T14:30:00Z"}'
      # ISO 8601 Duration Format
      timeout: 'PT5S'
    channel:
      $ref: '#/channels/NotifyOrderUpdates'
    messages:
      - $ref: '#/channels/NotifyOrderUpdates/messages/notifyOrder.message'
  initiateOrderDelivery:
    action: receive
    channel:
      $ref: '#/channels/OrderDeliveryInitiated'
    messages:
      - $ref: '#/channels/OrderDeliveryInitiated/messages/orderDeliveryInitiation.message'
    x-specmatic-side-effect:
      command: >
        test "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/orders/123?status=SHIPPED)" = "200"

components:
  messages:
    OrderRequest:
      name: OrderRequest
      title: An order request
      contentType: application/json
      payload:
        type: object
        required:
          - id
          - orderItems
        properties:
          id:
            type: integer
          orderItems:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                quantity:
                  type: integer
                price:
                  type: number
              required:
                - id
                - name
                - quantity
                - price
      examples:
        - name: NEW_ORDER
          payload:
            id: 10
            orderItems:
              - id: 1
                name: Macbook
                quantity: 1
                price: 2000
              - id: 2
                name: Iphone
                quantity: 1
                price: 1000
    Order:
      name: OrderToProcess
      title: An order that needs to be processed
      contentType: application/json
      payload:
        type: object
        required:
          - id
          - totalAmount
          - status
        properties:
          id:
            type: integer
          totalAmount:
            type: number
          status:
            type: string
            enum:
              - NEW
              - INPROGRESS
              - PROCESSED
              - FAILED
      examples:
        - name: NEW_ORDER
          payload:
            id: 10
            totalAmount: 3000
            status: PROCESSED
    CancelOrderRequest:
      name: CancelOrderRequest
      title: A cancel order request
      contentType: application/json
      payload:
        type: object
        required:
          - id
        properties:
          id:
            type: integer
      examples:
        - name: CANCEL_ORDER
          payload:
            id: 10
    CancellationReference:
      name: CancellationReference
      title: A cancellation reference in response to a cancel order request
      contentType: application/json
      payload:
        type: object
        required:
          - reference
          - status
        properties:
          reference:
            type: integer
          status:
            type: string
            enum:
              - CANCELLED
              - FAILED
      examples:
        - name: CANCEL_ORDER
          payload:
            reference: 10
            status: CANCELLED
    NotifyOrder:
      name: NotifyOrder
      title: An order notification
      contentType: application/json
      payload:
        type: object
        properties:
          id:
            type: integer
          status:
            type: string
            enum:
              - PROCESSED
              - CANCELLED
          timestamp:
            type: string
        required:
          - id
          - status
          - timestamp
      examples:
        - name: NOTIFY_ORDER
          payload:
            id: 123
            status: PROCESSED
            timestamp: "2025-04-12T14:30:00Z"

    OrderDeliveryInitiationTrigger:
      name: OrderDeliveryInitiationTrigger
      title: An order delivery initiation trigger
      contentType: application/json
      payload:
        type: object
        required:
          - orderId
          - deliveryAddress
          - deliveryDate
        properties:
          orderId:
            type: integer
          deliveryAddress:
            type: string
          deliveryDate:
            type: string
            format: date
      examples:
        - name: DELIVERY_INITIATED
          payload:
            orderId: 123
            deliveryAddress: "1234 Elm Street, Springfield"
            deliveryDate: "2025-04-14"
